### ISSUE TITLE
Register Write Closure Limitations

### ISSUE THREAD

**Issue by AdinAck** [stm32-rs/stm32-rs-nightlies#4]
I ran into an issue when writing to a register where I wanted to return a value from the write, like this:

```rust
let val = reg.write(|w| {
    T::set(w.field())
});
```

But, the signature of `write` forbids this:

```rust
pub fn write<F, T>(&self, f: F)
    where
        F: FnOnce(&mut REG::Writer) -> &mut W<REG>,
```

So I'm curious, why not change the signature to:

```rust
pub fn write<F, T>(&self, f: F) -> T
    where
        F: FnOnce(&mut REG::Writer) -> T
```

By implementing it like this:

```rust
pub fn write<F, T>(&self, f: F) -> T
where
    F: FnOnce(&mut W<REG>) -> T,
{
    let mut writer = W {
        bits: REG::RESET_VALUE & !REG::ONE_TO_MODIFY_FIELDS_BITMAP
            | REG::ZERO_TO_MODIFY_FIELDS_BITMAP,
        _reg: marker::PhantomData,
    };
    let result = f(&mut writer);

    self.register.set(writer.bits);

    result
}
```

Is there a drawback to this?

**Comment by adamgreig** [comment]
This is probably better asked on the [svd2rust repo](https://github.com/rust-embedded/svd2rust) - the code here is all generated with svd2rust based on the SVD files in the stm32-rs repo.

**Comment by AdinAck** [comment]
Oh, awesome, will do. Thanks!
